# Generated by Django 3.0.7 on 2020-06-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200619_1920'),
        ('users', '0003_auto_20200619_1846'),
    ]

    operations = [
    ]
