# Generated by Django 3.0.7 on 2020-06-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_photo'),
        ('users', '0004_merge_20200619_2206'),
    ]

    operations = [
    ]
