# Generated by Django 3.0.7 on 2020-06-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200619_2356'),
        ('users', '0005_merge_20200620_0023'),
    ]

    operations = [
    ]
