# Generated by Django 3.0.7 on 2020-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200620_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, default='test', max_length=128, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
