# Generated by Django 3.0.7 on 2020-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200620_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='little_avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='Малый аватар'),
        ),
    ]
