# Generated by Django 3.0.7 on 2020-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_little_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='little_avatar',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Малый аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Аватар'),
        ),
    ]
