# Generated by Django 3.0.7 on 2020-06-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Department')),
            ],
        ),
    ]
