# Generated by Django 3.0.7 on 2020-06-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование бейджа/награды')),
                ('uid', models.SlugField(verbose_name='Идентификатор')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('archive', models.NullBooleanField(default=False, verbose_name='Архивный')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование бейджа/награды')),
                ('uid', models.SlugField(verbose_name='Идентификатор')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('archive', models.NullBooleanField(default=False, verbose_name='Архивный')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('receiving_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата награждения')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Badge', verbose_name='Бейдж')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.Reward', verbose_name='Награда')),
            ],
        ),
    ]
