# Generated by Django 3.0.7 on 2020-06-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_auto_20200619_1920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(max_length=4000, verbose_name='Описание')),
                ('direction', models.CharField(choices=[('banking', 'Банковское обслуживание/Инвестиции'), ('security', 'Безопасность'), ('design', 'Дизайн'), ('technology', 'Новые технологии'), ('people', 'Сотрудники')], default='technology', max_length=16, verbose_name='Направление/Категория')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файлы презентации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('public', 'Публичное обсуждение'), ('expertise', 'Экспертиза'), ('ready_work', 'Формирование команды'), ('work', 'В работе'), ('finish', 'Завершено')], default='draft', max_length=16, verbose_name='Статус')),
                ('tender_type', models.CharField(choices=[('idea', 'Идея'), ('proposal', 'Предложение'), ('event', 'Мероприятие')], default='idea', max_length=16, verbose_name='Тип идеи/предложения')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Department', verbose_name='Зона видимости')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор идеи/предложения')),
            ],
        ),
    ]
