# Generated by Django 3.0.7 on 2020-06-20 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Наименование команды')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accelerator.Tender', verbose_name='Идея/Предложение')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан')),
                ('partner', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участник команды')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Наименование раунда')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта раунда')),
                ('finish_date', models.DateTimeField(verbose_name='Дата завершения раунда')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accelerator.Tender', verbose_name='Идея/Предложение')),
            ],
        ),
    ]
