# Generated by Django 3.0.7 on 2020-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0002_round_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('public', 'Публичное обсуждение'), ('expertise', 'Экспертиза'), ('ready_work', 'Формирование команды'), ('work', 'В работе'), ('finish', 'Завершено'), ('cancel', 'Отменена')], default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
