# Generated by Django 3.0.7 on 2020-06-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0004_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
