# Generated by Django 3.0.7 on 2020-06-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0005_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='presentation',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Файлы презентации'),
        ),
    ]
