# Generated by Django 3.0.7 on 2020-06-20 22:33

from django.db import migrations


def create_tenders(apps, schema_editor):
    """Создание предложений для тестов."""
    tenders = [
        {
            'caption': 'Корпоративу быть!',
            'description': 'Уважаемые коллеги, т.к. в связи с пандемией короновирусной инфекции \
                            (COVID-19) наш корпоратив был отменен, предлагаю собраться и отметить \
                            торжественну дату после снятия ограничений',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592692978/tender/u473_c6aqqq.jpg',
            'owner_id': 1,
        },
        {
            'caption': 'Август, горы, Грузия. Погнали?',
            'description': '',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592693247/tender/u17_vhjxmq.png',
            'owner_id': 1,
        },
        {
            'caption': 'Онлайн-тренировки во время короновируса. Записываемся',
            'description': '',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592693216/tender/u27_rs2avx.png',
            'owner_id': 1,
        },
        {
            'caption': 'Изучение китайского языка. Решайтесь!',
            'description': '',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592693169/tender/u16_b7onv4.png',
            'owner_id': 2,
        },
        {
            'caption': 'Поможем приюту для бездомных животных?',
            'description': '',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592693137/tender/u15_amyyqs.png',
            'owner_id': 3,
        },
        {
            'caption': '24 апреля. Большое приклчение в Большом театре',
            'description': '',
            'direction': 'people',
            'presentation': 'https://res.cloudinary.com/dcxovzp8n/image/upload/v1592693336/tender/u13_cx88pf.png',
            'owner_id': 3,
        }
    ]
    Tender = apps.get_model('accelerator', 'Tender')
    for tender_data in tenders:
        Tender.objects.create(**tender_data)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0006_auto_20200620_2230'),
    ]

    operations = [
        migrations.RunPython(create_tenders),
    ]
