# Generated by Django 3.0.7 on 2020-06-21 02:21

from django.db import migrations


def create_comments(apps, schema_editor):
    """Создание комментариев для теста."""
    comments = [
        'Супер!',
        'Я в деле!',
        'Хорошая инициатива. С нетерпением жду когда будет реализовано.',
        'А как скоро это может быть возможно?',
        'С радостью помог бы в реализации',
        'Мне кажется ничего не получится',
        'Руководящий состав не против?',
        'Было бы здорово',
        'А не получится как в прошлый раз?',
        'Кто будет спонсировать?',
        'А родственники могут воспользоваться?',
        'Я за',
        'Не понимаю кому это будет интересно',
        'В прошлый раз это не вышлло',
        'Лучше бы ДМС оплатили',
        'Давайте самостоятельно соберемся на пробежку',
        'Впишусь',
        'Подпишусь',
        'Не целесообразно',
        'Лучше бы пицца-пятницу устроили)',
        'А из зарпалты ничего потом не вычтут?',
        'Сколько баллов принесет участие в реализации?',
        'Это неинтересно',
        'Раньше было лучше',
        'Сильно зависит от руководства',
        'Не верю, что это возможно',
    ]
    Comment = apps.get_model('accelerator', 'Comment')
    Tender = apps.get_model('accelerator', 'Tender')
    Profile = apps.get_model('users', 'Profile')
    for comment in comments:
        Comment.objects.create(
            message=comment,
            author=Profile.objects.all().order_by('?').first(),
            tender=Tender.objects.all().order_by('?').first()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0007_auto_20200620_2233'),
    ]

    operations = [
        migrations.RunPython(create_comments),
    ]
